#!/usr/bin/env python3
import sys
from algoritmos import Algorithm
from time import time

ERR_MSG = "Error, uso: ./tdatp2 <E>|<A>|<A2> <datos.txt>"


def main():
    args = sys.argv[1:]
    if len(args) != 2:
        print(ERR_MSG)
        return

    try:
        algorithm = Algorithm(args[0]).func()
    except ValueError:
        print(ERR_MSG)
        return

    try:
        with open(args[1], "r") as f:
            datos = [float(x) for x in f.readlines()[2:]]
    except ValueError:
        print("Error, el archivo debe contener un número por línea")
    except FileNotFoundError:
        print("Error, no se pudo encontrar el archivo")
        return

    start = time()
    solution = algorithm(datos)
    end = time()
    print(f"{solution}: {len(solution)}")
    print((end - start) * 1000)


if __name__ == "__main__":
    main()
