#!/usr/bin/env python
import sys
from algoritmos.backtracking import backtracking
from algoritmos.greedy_consigna import greedy_consigna
from algoritmos.greedy_alternativo import greedy_alternativo

ALGORITHMS = {
    "E": backtracking,
    "A": greedy_consigna,
    "A2": greedy_alternativo,
}


def main():
    args = sys.argv[1:]
    if len(args) != 2 or args[0] not in ALGORITHMS:
        print("Error, uso: ./tdatp2 <E>|<A>|<A2> <datos.txt>")
        return

    try:
        with open(args[1], "r") as f:
            datos = f.readlines()
    except FileNotFoundError:
        print("Error, no se pudo encontrar el archivo")
        return

    print(ALGORITHMS[args[0]](datos))


if __name__ == "__main__":
    main()
